# Generated by Django 6.1.1 on 2026-09-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], max_length=20)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.IntegerField(help_text='Idade em anos')),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cep', models.CharField(help_text='CEP de onde o animal se encontra', max_length=9)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('disponivel_adocao', models.BooleanField(default=True)),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='tutores.tutor')),
            ],
        ),
    ]
