# Generated by Django 6.1.1 on 2026-10-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_adocao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
